alexa_site_verification:

analytics:
  google:
    tracking_id:
  provider: google-universal

atom_feed:
  path:

author:
  avatar: me.jpeg
  bio: Computer Science student interested in Programming Languages and Software Security. Linux and FOSS
    enthusiast.
  bitbucket:
  codepen:
  dribbble:
  email: gagan@gaganchandan.com
  employer:
  facebook:
  flickr:
  foursquare:
  github: gaganchandan
  google_plus:
  googlescholar:
  impactstory:
  instagram:
  keybase:
  lastfm:
  linkedin: https://www.linkedin.com/in/gagan-chandan-516430211/
  location: Bengaluru
  name: Gagan Chandan
  orcid:
  pinterest:
  pubmed:
  researchgate:
  soundcloud:
  stackexchange: '482007'
  steam:
  tumblr:
  twitter: gagan_chandan_
  uri:
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:

baseurl: ''

bing_site_verification:

breadcrumbs: no

category_archive:
  path: /categories/
  type: liquid

collections:
  portfolio:
    output: yes
    permalink: /:collection/:path/
  publications:
    output: yes
    permalink: /:collection/:path/
  talks:
    output: yes
    permalink: /:collection/:path/
  teaching:
    output: yes
    permalink: /:collection/:path/

comments:
  discourse:
    server:
  disqus:
    shortname:
  facebook:
    appid:
    colorscheme:
    num_posts:
  provider: staticman_v3

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:

  - scope:
      path: ''
      type: posts
    values:
      author_profile: yes
      comments: yes
      layout: single
      read_time: yes
      related: no
      share: yes

  - scope:
      path: ''
      type: pages
    values:
      author_profile: yes
      layout: single

  - scope:
      path: ''
      type: teaching
    values:
      author_profile: yes
      comments: yes
      layout: single
      share: yes

  - scope:
      path: ''
      type: publications
    values:
      author_profile: yes
      comments: yes
      layout: single
      share: yes

  - scope:
      path: ''
      type: portfolio
    values:
      author_profile: yes
      comment: yes
      layout: single
      share: yes

  - scope:
      path: ''
      type: talks
    values:
      author_profile: yes
      layout: talk
      share: yes

description: My personal website

encoding: utf-8

excerpt_separator: '

  '

exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

facebook:
  app_id:
  publisher:
  username:

future: yes

google_site_verification:

highlighter: rouge

include:
  - .htaccess
  - _pages
  - files

incremental: no

keep_files:
  - .git
  - .svn

kramdown:
  auto_ids: yes
  enable_coderay: no
  entity_output: as_char
  footnote_nr: 1
  hard_wrap: no
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

locale: en-US

lsi: no

markdown: kramdown

markdown_ext: markdown,mkdown,mkdn,mkd,md

name: Gagan Chandan

og_image:

permalink: /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

read_more: enabled

repository: gaganchandan/gaganchandan.github.io

sass:
  sass_dir: _sass
  style: compressed

social:
  links:
  name:
  type:

staticman:
  allowedFields:
    - name
    - email
    - url
    - message
  branch:
    - master
    - gh-pages
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  generatedFields:
    date:
      options:
        format: iso8601
      type: date
  moderation: yes
  path: _data/comments/{options.slug}
  requiredFields:
    - name
    - email
    - message
  transforms:
    email: md5

tag_archive:
  path: /tags/
  type: liquid

talkmap_link: no

teaser:

theme: jekyll-theme-architect

timezone: America/Los_Angeles

title: Gagan Chandan

title_separator: '-'

twitter:
  username:

url: //gaganchandan.com

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

words_per_minute: 160

yandex_site_verification:
